### ISSUE TITLE
I cannot seem to get this working.

### ISSUE THREAD

**Issue by griffinwebnet** [bygiro/Angular-Wizard-ByGiro#1]
Not sure what im doing wrong. I started out with your standard Jquery plugin and planned to write on complete rules but when i saw that you had already built it into an angular plugin i decided to go this route. sadly i cannot get it working. i have added the angular plugin and referenced it in my angular app via:
`var app = angular.module('HCare', ['ngRoute', 'LocalStorageModule', 'ByGiro.wizard']);` 

this causes no errors. 

In my controller i have:
`app.controller('NewUserController', function ($scope) {`
`$scope.wizardOptions = {`
`onCompleted: function () {`
`console.log("Done");`
`}`
`};`
`});`

this controller is attached to the new user route

`app.config(function ($routeProvider) {`
`$routeProvider.when('/new_user', {`
`controller: 'NewUserController',`
`templateUrl: './ng/views/administration/users_new.html'`
`})`
`});`

The wizard is added int he route view via:

`<div data-wizard-init>`
`<ul class="steps">`
`<li data-step="1">Account</li>`
`<li data-step="2">Personal</li>`
`<li data-step="3">Schedule</li>`
`</ul>`
`<div class="steps-content">`
`<div data-step="1">`
`<h4>No Data To Show</h4>`
`</div>`
`<div data-step="2">`
`<h4>No Data To Show</h4>`
`</div>`
`<div data-step="3">`
`<h4>No Data To Show</h4>`
`</div>`
`</div>`
`</div>`

Now the Wizard itself works but pressing complete does not echo "Done" into the console, nor does it trigger a function if i write a separate function to trigger. what am i missing?

**Comment by bygiro** [comment]
it doesn't work because you forgot to pass the wizardoptions to the wizard.
add this attribute: data-bgw-options="wizardOptions" to the `<div data-wizard-init>`, so it should be:
`<div data-bgw-options="wizardOptions" data-wizard-init>`

**Comment by griffinwebnet** [comment]
ah well i had removed that becasue including it causes my wizard to be empty. no steps no nothing. i get an empty wizard. I dont want to add the wizard content in the controller i want to add it in the view there is almost 1000 lines of code involved in this wizard, id prefer not to add that in my controller. is there a way i can pass this option without causing the creation of an empty wizard?

**Comment by griffinwebnet** [comment]
nevermind i got it now needed to switch `data-wizard-init` to `data-bgw-wizard-init` all working now.

Last thing, is there a simple way of making the seps refuse to move forward based on form validation? there doesnt seem to be any real documentation on options aforded by the plugin. thanks in advance

**Comment by bygiro** [comment]
there is a function called "checkStep" it should return true/false to allow navigation between steps, there you can trigger and check all the validations you want

**Comment by griffinwebnet** [comment]
thank you! if i have any other issues i will let you know. amazing work by the way. by far the nicest looking wizard plugin ive seen, and simple to adapt themeing!
